# environment.yml - conda environment setup
# -  this is creating conda environment called dj-fm-app
# To create environment based on this file
#
#     $ conda env create -f environment.yml
#
# To activate this environment, use
#
#     $ conda activate dj-fm-app
#
# To deactivate an active environment, use
#
#     $ conda deactivate
#
# To verify packages installed
#
#     $ pip list
#
# To update your existing environment in place - without recreating it
#
#     $ conda env update --name dj-fm-app --file environment.yml --prune
#


name: dj-fm-app
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi[all]
      - transformers
      - torch
      - sqlmodel
